services:
  spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring_club
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=springpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=spring_club
      - POSTGRES_USER=springuser
      - POSTGRES_PASSWORD=springpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springuser -d spring_club"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - PGWEB_DATABASE_URL=postgres://springuser:springpass@db:5432/spring_club?sslmode=disable
    command: pgweb --bind=0.0.0.0 --listen=8081

volumes:
  postgres_data: